### ISSUE TITLE
one suggestion function getQRCodeGoogleUrl

### ISSUE THREAD

**Issue by lyragosa** [PHPGangsta/GoogleAuthenticator#12]
im lazy to submit code so i just write this issue. sorry for it. 

That is the modify
```

    public function getQRCodeGoogleUrl($name, $secret, $title) {
        $urlencoded = urlencode('otpauth://totp/'.$name.'?secret='.$secret.'&issuer='.$title);
        return 'https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl='.$urlencoded.'';
    }

```

i add $title parameter, and use the key 'issuer='  . this parameter make the phone app show your website name in the top of the random code instead of in the bottom.

**Comment by RobThree** [comment]
See https://github.com/PHPGangsta/GoogleAuthenticator/pull/15; you need to correctly encode the values before encoding the entire url as well.

**Comment by PHPGangsta** [comment]
The $title / issuer parameter has been added in March 2015 by @yanniks: https://github.com/PHPGangsta/GoogleAuthenticator/blob/022046934a85217739b4e7610a37fcc8ffdf986e/PHPGangsta/GoogleAuthenticator.php#L102
