### ISSUE TITLE
base32Encode function!

### ISSUE THREAD

**Issue by abmmhasan** [PHPGangsta/GoogleAuthenticator#19]
I think it can be removed from main class file. Though for other's help you can make another file. Don't see reasons to keep that function in main class file.

**Comment by RobThree** [comment]
See https://github.com/PHPGangsta/GoogleAuthenticator/issues/11:
> * The `_base32Encode()` method is never used and should be removed.

https://github.com/PHPGangsta/GoogleAuthenticator/issues/11#issuecomment-80761276:
> You are right, _base32Encode() is not used in the current version of the code, I think it was used in one of the first (internal) versions before putting it on GitHub. It can be removed.

**Comment by PHPGangsta** [comment]
I removed the function, it was not used (anymore): 022046934a85217739b4e7610a37fcc8ffdf986e
