### ISSUE TITLE
array_rand is not random enough for generating safe unique strings

### ISSUE THREAD

**Issue by alexjeen** [PHPGangsta/GoogleAuthenticator#20]
See comments @ 

http://php.net/manual/en/function.array-rand.php

It is not distributed properly, maybe use a function like this (taken from phpass library):

	function get_random_bytes($count)
	{
		$output = '';
		if (is_readable('/dev/urandom') &&
		    ($fh = @fopen('/dev/urandom', 'rb'))) {
			$output = fread($fh, $count);
			fclose($fh);
		}

		if (strlen($output) < $count) {
			$output = '';
			for ($i = 0; $i < $count; $i += 16) {
				$this->random_state =
				    md5(microtime() . $this->random_state);
				$output .=
				    pack('H*', md5($this->random_state));
			}
			$output = substr($output, 0, $count);
		}

		return $output;
	}

**Comment by PHPGangsta** [comment]
If mcrypt or openssl are available, they are now used. Thanks to @aoighost. See PR #22
