### ISSUE TITLE
can I re-use my Google 2FA secret key?

### ISSUE THREAD

**Issue by jhaar** [PHPGangsta/GoogleAuthenticator#27]
Hi there

Not really an issue - more of a question

I recorded my Google 2FA secret key (it's 32-char base32 I think?) and would like to re-use it within my (working) php-GoogleAuthenticator web application. However, the keys generated by GoogleAuthenticator appear to be 16 char and all in uppercase (vs Google's lowercase)

Is there a way to convert one to the other so that I can log into both my GMail and own web application using the same 2FA token? 

Besides this, your code works splendidly :-)

Thanks

Jason

**Comment by budwig** [comment]
jhaar, it's super easy to make the code in any length you want.
Check the code in GoogleAuthenticator.php, it's set to 16 as default.:
public function createSecret($secretLength = 16)

And in the example1.php, you can change the line:
$secret = $ga->createSecret();
to
$secret = $ga->createSecret(32);
or
$secret = strtolower ($ga->createSecret(32)); // will be in lowercase, however UPPERCASE looks nicer :)

I hope this helps.

**Comment by jhaar** [comment]
awesome! Works just as you said :-)

Thanks!
