### ISSUE TITLE
Why key can validate multiple use ?

### ISSUE THREAD

**Issue by parnus01** [PHPGangsta/GoogleAuthenticator#34]
when i validate key and success login , after i logout why it can use same key to validate

How can i implement it to expire key now after validate success.

thnak you

**Comment by RobThree** [comment]
See [this explanation](https://github.com/RobThree/TwoFactorAuth/issues/9#issuecomment-245847820)

**Comment by PHPGangsta** [comment]
The explanation of @RobThree is super good.

You have to take care of that yourself. That's why there is a text in my README that says:
- For a secure installation you have to make sure that used codes cannot be reused (replay-attack).
