### ISSUE TITLE
What is meaning of 'Blog' parameter in the example?

### ISSUE THREAD

**Issue by yupitomets** [PHPGangsta/GoogleAuthenticator#35]
In example.php there is mystic variable for me 'Blog'. Could you please explain what is that means and if it can be changed to other value?

$qrCodeUrl = $ga->getQRCodeGoogleUrl('Blog', $secret);

**Comment by PHPGangsta** [comment]
The first parameter of the function getQRCodeGoogleUrl() is a "name" for the QRCode:
https://github.com/PHPGangsta/GoogleAuthenticator/blob/master/PHPGangsta/GoogleAuthenticator.php#L77

Das exakte Format ist hier beschrieben:
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

If you scan the resulting QRCode image with your mobile phone, the name will be displayed, like this:
![Image Authenticator](http://media.idownloadblog.com/wp-content/uploads/2013/09/google-authenticator-ss-576x1024.png)

The name helps you to distinguish the TOTP-Token in the Authenticator App, if you have multiple ones. It can be an email address, or a URL, or anything.
