### ISSUE TITLE
Add another author to this repository

### ISSUE THREAD

**Issue by alexjeen** [PHPGangsta/GoogleAuthenticator#37]
You have 8 pull requests and several issues. Wouldn't it be  good to add somebody that can merge those pull requests, write some tests, answer the issues etc. As it's the only good Google Authenticator library out there..

We have some time to put one of our programmers on it to improve this library.

**Comment by RobThree** [comment]
> As it's the only good Google Authenticator library out there

I [disagree](https://github.com/RobThree/TwoFactorAuth) (Disclaimer: author here). Mine is based on PHPGangsta's but has a lot less issues this one currently still has.

**Comment by alexjeen** [comment]
I disagree as well as we now use (it was hard to find on Google, also your library is hard to find :)):

https://github.com/antonioribeiro/google2fa

Thanks for the link we will also consider your library.
