### ISSUE TITLE
Google Charts API is deprecated and not available since March 19, 2019

### ISSUE THREAD

**Issue by luxemate** [PHPGangsta/GoogleAuthenticator#62]
Google Charts API has [a nice warning](https://developers.google.com/chart/image/) about that:
>Warning: This API is deprecated and is scheduled to be turned off on March 14, 2019. Please use the actively maintained Google Charts API instead.

And returns 502 instead of qr-code:
![2019-03-19_09-19](https://user-images.githubusercontent.com/1465003/54587246-35024800-4a28-11e9-937f-7e282925344a.png)

**Comment by svoorn** [comment]
Just replace line `112` with `return "https://api.qrserver.com/v1/create-qr-code/?data=$urlencoded&size=${width}x${height}&ecc=$level";`

**Comment by PHPGangsta** [comment]
Thanks, has been commited: 4f80232ee76e78eae9977236ee8c7fda7518322a

**Comment by luxemate** [comment]
Thanks! Would be great to also have a way to define your own URL for QR code generation (we backed off to our internal URL), to have a choice between open solutions or not rely on them altogether, as they work today and might not work tomorrow. But that's a different story. :)

**Comment by PHPGangsta** [comment]
Of cause you can generate your own QR code URL. Just use the secret (via `createSecret()`) and build your own URL. The built-in function is just a small help for convenience, but nobody is forced to use it 😄
