### ISSUE TITLE
Avoid TOTP code replay attacks

### ISSUE THREAD

**Issue by greggles** [PHPGangsta/GoogleAuthenticator#9]
As far as I can tell, GoogleAuthenticator library doesn't prevent a replay attack. 

For this to be relevant we have to assume that either the victim is using an insecure network or has malware on their computer - both of which are not ideal, but happen more often than we'd like.

Would it be possible for GoogleAuthenticator library itself to prevent a replay? My guess is that the library doesn't have any way to persist data so it can't really prevent this kind of attack, but maybe you have ideas on that.

If it's not possible to solve in the library, then I suggest adding a note to the README to encourage people who use the library to add a feature to their code to prevent replay.

**Comment by PHPGangsta** [comment]
As greggles said, it should be done outside of this library. The application should use its favorite storage for remembering used codes, and reject them if they are tried again. So it "works as designed".
